### ISSUE TITLE
Old TF versions on OS X Sierra

### ISSUE THREAD

**Issue by avandendorpe** [kamatama41/tfenv#51] opened 2017-05-30 17:54 UTC
Old versions of Terraform compiled with Go 1.6.x (or older) exhibit inconsistent problematic behavior in OS X Sierra. This relates to https://github.com/golang/go/issues/16570.

Specifically, I encountered "unexpected signal during runtime execution" during a terraform plan with 0.6.16, while on other identical runs it would sometimes complete, or sometimes hang for 10min+.

Given that the binaries tfenv is downloading appear to be essentially incompatible with Sierra, I would suggest tfenv warn the user on install/selection of these builds. The above-and-beyond answer would be to add functionality to build from source à la RVM, but that might be overkill.

**Comment by kamatama41** [comment] 2017-06-01 03:31
@avandendorpe 
Hi, thank you for your suggestion.
Do you know which version of Terraform started using Go 1.7+?

**Comment by avandendorpe** [comment] 2017-06-05 19:31
I do not, and am not a go dev so unsure how best to check. `strings` on the binaries shows Go 1.6 definitely for Terraform v0.7.0 and down, but does not print meaningful output on v0.7.1 and up.

**Comment by kamatama41** [comment] 2017-11-01 16:31
@avandendorpe 
Sorry for late reply. Although I considered this feature, I decide not to implement it because the problem is not so critical for us (at least for me). We can upgrade Terraform if current version is incompatible. Therefore, in order to show warning, I don't want to keep maintaining a list of MacOS version with supported Terraform versions.
Although I'll close the issue, of course, you can create a PR and reopen if you really need it :)

**Closed by kamatama41** 2017-11-01 16:31 UTC
